// 健身 & 脊椎治疗专业词汇 - 200个常用单词（含例句）
const fitnessWords = [
  // ==================== 身体部位 Body Parts ====================
  { word: "spine", meaning: "脊柱", category: "anatomy", emoji: "🦴", example: "Keep your spine straight during the exercise.", exampleCn: "运动时保持脊柱挺直。" },
  { word: "vertebra", meaning: "椎骨", category: "anatomy", emoji: "🦴", example: "The human spine has 33 vertebrae.", exampleCn: "人类脊柱有33块椎骨。" },
  { word: "cervical", meaning: "颈椎的", category: "anatomy", emoji: "🦒", example: "Cervical pain is common among office workers.", exampleCn: "颈椎疼痛在办公室工作者中很常见。" },
  { word: "thoracic", meaning: "胸椎的", category: "anatomy", emoji: "🫁", example: "The thoracic spine connects to the ribs.", exampleCn: "胸椎与肋骨相连。" },
  { word: "lumbar", meaning: "腰椎的", category: "anatomy", emoji: "🦴", example: "Lumbar support is important for sitting.", exampleCn: "腰椎支撑对坐姿很重要。" },
  { word: "sacrum", meaning: "骶骨", category: "anatomy", emoji: "🦴", example: "The sacrum is located at the base of the spine.", exampleCn: "骶骨位于脊柱底部。" },
  { word: "coccyx", meaning: "尾骨", category: "anatomy", emoji: "🦴", example: "He injured his coccyx in the fall.", exampleCn: "他摔倒时伤到了尾骨。" },
  { word: "disc", meaning: "椎间盘", category: "anatomy", emoji: "⚪", example: "The disc acts as a cushion between vertebrae.", exampleCn: "椎间盘起到椎骨之间缓冲的作用。" },
  { word: "joint", meaning: "关节", category: "anatomy", emoji: "🔗", example: "Warm up your joints before exercise.", exampleCn: "运动前先活动关节。" },
  { word: "ligament", meaning: "韧带", category: "anatomy", emoji: "🪢", example: "She tore a ligament in her knee.", exampleCn: "她撕裂了膝盖的韧带。" },
  { word: "tendon", meaning: "肌腱", category: "anatomy", emoji: "🪢", example: "The Achilles tendon is very strong.", exampleCn: "跟腱非常强壮。" },
  { word: "cartilage", meaning: "软骨", category: "anatomy", emoji: "⚪", example: "Cartilage protects the ends of bones.", exampleCn: "软骨保护骨头末端。" },
  { word: "muscle", meaning: "肌肉", category: "anatomy", emoji: "💪", example: "Building muscle takes time and effort.", exampleCn: "增肌需要时间和努力。" },
  { word: "bone", meaning: "骨头", category: "anatomy", emoji: "🦴", example: "Calcium is essential for strong bones.", exampleCn: "钙对强健骨骼至关重要。" },
  { word: "nerve", meaning: "神经", category: "anatomy", emoji: "⚡", example: "The nerve sends signals to the brain.", exampleCn: "神经向大脑发送信号。" },
  { word: "pelvis", meaning: "骨盆", category: "anatomy", emoji: "🦴", example: "The pelvis supports the upper body.", exampleCn: "骨盆支撑上半身。" },
  { word: "shoulder", meaning: "肩膀", category: "anatomy", emoji: "🤷", example: "Relax your shoulders when you stretch.", exampleCn: "拉伸时放松肩膀。" },
  { word: "hip", meaning: "髋部", category: "anatomy", emoji: "🦵", example: "Hip mobility is important for squats.", exampleCn: "髋部灵活性对深蹲很重要。" },
  { word: "knee", meaning: "膝盖", category: "anatomy", emoji: "🦵", example: "Don't let your knees go past your toes.", exampleCn: "不要让膝盖超过脚趾。" },
  { word: "ankle", meaning: "脚踝", category: "anatomy", emoji: "🦶", example: "He sprained his ankle while running.", exampleCn: "他跑步时扭伤了脚踝。" },
  { word: "wrist", meaning: "手腕", category: "anatomy", emoji: "✋", example: "Keep your wrists straight when lifting.", exampleCn: "举重时保持手腕伸直。" },
  { word: "elbow", meaning: "肘部", category: "anatomy", emoji: "💪", example: "Bend your elbows at 90 degrees.", exampleCn: "将肘部弯曲成90度。" },
  { word: "neck", meaning: "颈部", category: "anatomy", emoji: "🦒", example: "Stretch your neck gently after work.", exampleCn: "工作后轻轻拉伸颈部。" },
  { word: "back", meaning: "背部", category: "anatomy", emoji: "🔙", example: "A strong back prevents injuries.", exampleCn: "强壮的背部可以预防受伤。" },
  { word: "core", meaning: "核心肌群", category: "anatomy", emoji: "🎯", example: "Engage your core during the plank.", exampleCn: "做平板支撑时收紧核心。" },
  { word: "abdomen", meaning: "腹部", category: "anatomy", emoji: "🫃", example: "Tighten your abdomen when lifting.", exampleCn: "举重时收紧腹部。" },
  { word: "glutes", meaning: "臀肌", category: "anatomy", emoji: "🍑", example: "Squats are great for your glutes.", exampleCn: "深蹲对臀肌很有效。" },
  { word: "hamstring", meaning: "腘绳肌", category: "anatomy", emoji: "🦵", example: "Stretch your hamstrings after running.", exampleCn: "跑步后拉伸腘绳肌。" },
  { word: "quadriceps", meaning: "股四头肌", category: "anatomy", emoji: "🦵", example: "Lunges target the quadriceps.", exampleCn: "弓步锻炼股四头肌。" },
  { word: "calf", meaning: "小腿肌", category: "anatomy", emoji: "🦵", example: "My calves are sore from hiking.", exampleCn: "我的小腿因为徒步而酸痛。" },
  { word: "biceps", meaning: "二头肌", category: "anatomy", emoji: "💪", example: "Curls build your biceps.", exampleCn: "弯举锻炼二头肌。" },
  { word: "triceps", meaning: "三头肌", category: "anatomy", emoji: "💪", example: "Dips are good for triceps.", exampleCn: "臂屈伸对三头肌有好处。" },
  { word: "deltoid", meaning: "三角肌", category: "anatomy", emoji: "🔺", example: "Shoulder press works the deltoids.", exampleCn: "肩推锻炼三角肌。" },
  { word: "trapezius", meaning: "斜方肌", category: "anatomy", emoji: "🔺", example: "Shrugs strengthen the trapezius.", exampleCn: "耸肩加强斜方肌。" },
  { word: "latissimus", meaning: "背阔肌", category: "anatomy", emoji: "🦅", example: "Pull-ups develop the latissimus.", exampleCn: "引体向上锻炼背阔肌。" },
  { word: "pectorals", meaning: "胸肌", category: "anatomy", emoji: "🫁", example: "Push-ups build your pectorals.", exampleCn: "俯卧撑锻炼胸肌。" },
  { word: "obliques", meaning: "腹斜肌", category: "anatomy", emoji: "↗️", example: "Side planks target the obliques.", exampleCn: "侧平板支撑针对腹斜肌。" },
  { word: "rotator cuff", meaning: "肩袖", category: "anatomy", emoji: "🔄", example: "Warm up your rotator cuff before lifting.", exampleCn: "举重前热身肩袖。" },
  { word: "fascia", meaning: "筋膜", category: "anatomy", emoji: "🎀", example: "Foam rolling releases the fascia.", exampleCn: "泡沫轴可以放松筋膜。" },
  { word: "tissue", meaning: "组织", category: "anatomy", emoji: "🧬", example: "Soft tissue needs time to recover.", exampleCn: "软组织需要时间恢复。" },

  // ==================== 健身动作 Exercises ====================
  { word: "squat", meaning: "深蹲", category: "exercise", emoji: "🏋️", example: "Squat with your feet shoulder-width apart.", exampleCn: "双脚与肩同宽做深蹲。" },
  { word: "deadlift", meaning: "硬拉", category: "exercise", emoji: "🏋️", example: "Keep your back flat during the deadlift.", exampleCn: "硬拉时保持背部平直。" },
  { word: "bench press", meaning: "卧推", category: "exercise", emoji: "🏋️", example: "The bench press works your chest.", exampleCn: "卧推锻炼胸部。" },
  { word: "lunge", meaning: "弓步", category: "exercise", emoji: "🚶", example: "Do lunges to strengthen your legs.", exampleCn: "做弓步来加强腿部力量。" },
  { word: "plank", meaning: "平板支撑", category: "exercise", emoji: "🧘", example: "Hold the plank for 60 seconds.", exampleCn: "平板支撑保持60秒。" },
  { word: "push-up", meaning: "俯卧撑", category: "exercise", emoji: "💪", example: "Do 20 push-ups every morning.", exampleCn: "每天早上做20个俯卧撑。" },
  { word: "pull-up", meaning: "引体向上", category: "exercise", emoji: "🧗", example: "Pull-ups are challenging but effective.", exampleCn: "引体向上很有挑战性但很有效。" },
  { word: "row", meaning: "划船", category: "exercise", emoji: "🚣", example: "Rows strengthen your back muscles.", exampleCn: "划船动作加强背部肌肉。" },
  { word: "curl", meaning: "弯举", category: "exercise", emoji: "💪", example: "Bicep curls with dumbbells.", exampleCn: "用哑铃做二头肌弯举。" },
  { word: "extension", meaning: "伸展", category: "exercise", emoji: "➡️", example: "Leg extension targets the quadriceps.", exampleCn: "腿部伸展针对股四头肌。" },
  { word: "flexion", meaning: "屈曲", category: "exercise", emoji: "⬅️", example: "Hip flexion is important for mobility.", exampleCn: "髋部屈曲对灵活性很重要。" },
  { word: "rotation", meaning: "旋转", category: "exercise", emoji: "🔄", example: "Add rotation to work your core.", exampleCn: "加入旋转来锻炼核心。" },
  { word: "crunch", meaning: "卷腹", category: "exercise", emoji: "🧘", example: "Crunches target your abs.", exampleCn: "卷腹针对腹肌。" },
  { word: "dip", meaning: "臂屈伸", category: "exercise", emoji: "⬇️", example: "Dips work your triceps and chest.", exampleCn: "臂屈伸锻炼三头肌和胸肌。" },
  { word: "press", meaning: "推举", category: "exercise", emoji: "⬆️", example: "Overhead press builds shoulder strength.", exampleCn: "过头推举增强肩部力量。" },
  { word: "fly", meaning: "飞鸟", category: "exercise", emoji: "🦅", example: "Chest fly isolates the pectorals.", exampleCn: "飞鸟动作孤立锻炼胸肌。" },
  { word: "shrug", meaning: "耸肩", category: "exercise", emoji: "🤷", example: "Shrugs build your upper traps.", exampleCn: "耸肩锻炼上斜方肌。" },
  { word: "raise", meaning: "举起", category: "exercise", emoji: "🙋", example: "Lateral raise works the shoulders.", exampleCn: "侧平举锻炼肩膀。" },
  { word: "stretch", meaning: "拉伸", category: "exercise", emoji: "🤸", example: "Always stretch before exercising.", exampleCn: "运动前一定要拉伸。" },
  { word: "warm-up", meaning: "热身", category: "exercise", emoji: "🔥", example: "A good warm-up prevents injuries.", exampleCn: "良好的热身可以预防受伤。" },
  { word: "cool-down", meaning: "放松", category: "exercise", emoji: "❄️", example: "Don't skip the cool-down after training.", exampleCn: "训练后不要跳过放松环节。" },
  { word: "cardio", meaning: "有氧运动", category: "exercise", emoji: "❤️", example: "Cardio improves heart health.", exampleCn: "有氧运动改善心脏健康。" },
  { word: "HIIT", meaning: "高强度间歇训练", category: "exercise", emoji: "⚡", example: "HIIT burns calories quickly.", exampleCn: "HIIT快速燃烧卡路里。" },
  { word: "circuit training", meaning: "循环训练", category: "exercise", emoji: "🔁", example: "Circuit training keeps your heart rate up.", exampleCn: "循环训练保持心率。" },
  { word: "resistance training", meaning: "阻力训练", category: "exercise", emoji: "💪", example: "Resistance training builds muscle.", exampleCn: "阻力训练增肌。" },
  { word: "isometric", meaning: "等长收缩", category: "exercise", emoji: "🧱", example: "Plank is an isometric exercise.", exampleCn: "平板支撑是等长收缩运动。" },
  { word: "concentric", meaning: "向心收缩", category: "exercise", emoji: "🎯", example: "Lifting is the concentric phase.", exampleCn: "举起是向心收缩阶段。" },
  { word: "eccentric", meaning: "离心收缩", category: "exercise", emoji: "↔️", example: "Lowering slowly builds eccentric strength.", exampleCn: "慢慢放下增强离心力量。" },
  { word: "compound", meaning: "复合动作", category: "exercise", emoji: "🔗", example: "Squats are a compound movement.", exampleCn: "深蹲是复合动作。" },
  { word: "isolation", meaning: "孤立动作", category: "exercise", emoji: "1️⃣", example: "Curls are an isolation exercise.", exampleCn: "弯举是孤立动作。" },

  // ==================== 健身器材 Equipment ====================
  { word: "dumbbell", meaning: "哑铃", category: "equipment", emoji: "🏋️", example: "Grab a pair of dumbbells.", exampleCn: "拿一对哑铃。" },
  { word: "barbell", meaning: "杠铃", category: "equipment", emoji: "🏋️", example: "Load the barbell with weights.", exampleCn: "给杠铃加上重量。" },
  { word: "kettlebell", meaning: "壶铃", category: "equipment", emoji: "🔔", example: "Kettlebell swings are great for cardio.", exampleCn: "壶铃摆动很适合有氧。" },
  { word: "treadmill", meaning: "跑步机", category: "equipment", emoji: "🏃", example: "Run on the treadmill for 20 minutes.", exampleCn: "在跑步机上跑20分钟。" },
  { word: "elliptical", meaning: "椭圆机", category: "equipment", emoji: "⭕", example: "The elliptical is low impact.", exampleCn: "椭圆机对关节冲击小。" },
  { word: "stationary bike", meaning: "健身车", category: "equipment", emoji: "🚴", example: "Warm up on the stationary bike.", exampleCn: "在健身车上热身。" },
  { word: "rowing machine", meaning: "划船机", category: "equipment", emoji: "🚣", example: "The rowing machine works your whole body.", exampleCn: "划船机锻炼全身。" },
  { word: "cable machine", meaning: "缆绳器械", category: "equipment", emoji: "🔌", example: "Use the cable machine for chest fly.", exampleCn: "用缆绳器械做飞鸟。" },
  { word: "resistance band", meaning: "弹力带", category: "equipment", emoji: "🎀", example: "Resistance bands are portable.", exampleCn: "弹力带便于携带。" },
  { word: "foam roller", meaning: "泡沫轴", category: "equipment", emoji: "🧻", example: "Use a foam roller to release tight muscles.", exampleCn: "用泡沫轴放松紧绷的肌肉。" },
  { word: "yoga mat", meaning: "瑜伽垫", category: "equipment", emoji: "🧘", example: "Lay your yoga mat on the floor.", exampleCn: "把瑜伽垫铺在地上。" },
  { word: "medicine ball", meaning: "药球", category: "equipment", emoji: "⚽", example: "Throw the medicine ball against the wall.", exampleCn: "把药球扔向墙壁。" },
  { word: "stability ball", meaning: "稳定球", category: "equipment", emoji: "🔵", example: "Sit on the stability ball for core work.", exampleCn: "坐在稳定球上锻炼核心。" },
  { word: "pull-up bar", meaning: "引体向上杆", category: "equipment", emoji: "➖", example: "Install a pull-up bar at home.", exampleCn: "在家安装引体向上杆。" },
  { word: "bench", meaning: "训练凳", category: "equipment", emoji: "🪑", example: "Adjust the bench to an incline.", exampleCn: "把训练凳调成斜面。" },
  { word: "rack", meaning: "架子", category: "equipment", emoji: "🗄️", example: "Place the barbell back on the rack.", exampleCn: "把杠铃放回架子上。" },
  { word: "plate", meaning: "杠铃片", category: "equipment", emoji: "⚫", example: "Add more plates for heavier weight.", exampleCn: "加更多杠铃片增加重量。" },
  { word: "grip", meaning: "握把/握法", category: "equipment", emoji: "✊", example: "Use an overhand grip.", exampleCn: "使用正握。" },
  { word: "strap", meaning: "绑带", category: "equipment", emoji: "🎗️", example: "Use straps for heavy deadlifts.", exampleCn: "大重量硬拉时使用绑带。" },
  { word: "mat", meaning: "垫子", category: "equipment", emoji: "🟦", example: "Exercise on a mat for comfort.", exampleCn: "在垫子上运动更舒适。" },

  // ==================== 脊椎治疗 Chiropractic ====================
  { word: "adjustment", meaning: "矫正", category: "chiropractic", emoji: "🔧", example: "The chiropractor made an adjustment.", exampleCn: "脊椎治疗师进行了矫正。" },
  { word: "manipulation", meaning: "手法治疗", category: "chiropractic", emoji: "🤲", example: "Spinal manipulation can relieve pain.", exampleCn: "脊椎手法治疗可以缓解疼痛。" },
  { word: "subluxation", meaning: "半脱位", category: "chiropractic", emoji: "⚠️", example: "A subluxation can cause nerve issues.", exampleCn: "半脱位可能导致神经问题。" },
  { word: "alignment", meaning: "对齐", category: "chiropractic", emoji: "📐", example: "Good alignment reduces pain.", exampleCn: "良好的对齐减少疼痛。" },
  { word: "misalignment", meaning: "错位", category: "chiropractic", emoji: "↗️", example: "Misalignment can cause chronic pain.", exampleCn: "错位可能导致慢性疼痛。" },
  { word: "mobilization", meaning: "松动术", category: "chiropractic", emoji: "🔄", example: "Joint mobilization improves flexibility.", exampleCn: "关节松动术提高灵活性。" },
  { word: "spinal cord", meaning: "脊髓", category: "chiropractic", emoji: "🧠", example: "The spinal cord carries nerve signals.", exampleCn: "脊髓传递神经信号。" },
  { word: "herniated disc", meaning: "椎间盘突出", category: "chiropractic", emoji: "💥", example: "A herniated disc can be very painful.", exampleCn: "椎间盘突出可能非常疼痛。" },
  { word: "bulging disc", meaning: "椎间盘膨出", category: "chiropractic", emoji: "🎈", example: "A bulging disc may press on nerves.", exampleCn: "椎间盘膨出可能压迫神经。" },
  { word: "sciatica", meaning: "坐骨神经痛", category: "chiropractic", emoji: "⚡", example: "Sciatica causes pain down the leg.", exampleCn: "坐骨神经痛导致腿部疼痛。" },
  { word: "scoliosis", meaning: "脊柱侧弯", category: "chiropractic", emoji: "〰️", example: "Scoliosis is a curved spine.", exampleCn: "脊柱侧弯是脊柱弯曲。" },
  { word: "kyphosis", meaning: "驼背", category: "chiropractic", emoji: "🔙", example: "Kyphosis causes a rounded upper back.", exampleCn: "驼背导致上背部圆弧。" },
  { word: "lordosis", meaning: "腰椎前凸", category: "chiropractic", emoji: "🔙", example: "Excessive lordosis is called swayback.", exampleCn: "过度腰椎前凸叫做凹背。" },
  { word: "posture", meaning: "姿势", category: "chiropractic", emoji: "🧍", example: "Good posture prevents back pain.", exampleCn: "良好的姿势预防背痛。" },
  { word: "range of motion", meaning: "活动范围", category: "chiropractic", emoji: "↔️", example: "Improve your range of motion with stretching.", exampleCn: "通过拉伸提高活动范围。" },
  { word: "flexibility", meaning: "柔韧性", category: "chiropractic", emoji: "🤸", example: "Yoga improves flexibility.", exampleCn: "瑜伽提高柔韧性。" },
  { word: "stiffness", meaning: "僵硬", category: "chiropractic", emoji: "🧱", example: "Morning stiffness is common.", exampleCn: "早晨僵硬很常见。" },
  { word: "inflammation", meaning: "炎症", category: "chiropractic", emoji: "🔥", example: "Ice reduces inflammation.", exampleCn: "冰敷减轻炎症。" },
  { word: "degeneration", meaning: "退化", category: "chiropractic", emoji: "📉", example: "Disc degeneration happens with age.", exampleCn: "椎间盘退化随年龄发生。" },
  { word: "rehabilitation", meaning: "康复", category: "chiropractic", emoji: "🏥", example: "Rehabilitation takes time and patience.", exampleCn: "康复需要时间和耐心。" },
  { word: "therapy", meaning: "治疗", category: "chiropractic", emoji: "💊", example: "Physical therapy helps recovery.", exampleCn: "物理治疗帮助恢复。" },
  { word: "diagnosis", meaning: "诊断", category: "chiropractic", emoji: "🔍", example: "Get a proper diagnosis first.", exampleCn: "首先要得到正确的诊断。" },
  { word: "assessment", meaning: "评估", category: "chiropractic", emoji: "📋", example: "The assessment showed muscle weakness.", exampleCn: "评估显示肌肉无力。" },
  { word: "treatment", meaning: "治疗方案", category: "chiropractic", emoji: "📝", example: "The treatment plan includes exercises.", exampleCn: "治疗方案包括练习。" },
  { word: "X-ray", meaning: "X光", category: "chiropractic", emoji: "📷", example: "The X-ray showed no fracture.", exampleCn: "X光显示没有骨折。" },
  { word: "MRI", meaning: "核磁共振", category: "chiropractic", emoji: "🧲", example: "An MRI gives detailed images.", exampleCn: "核磁共振提供详细图像。" },
  { word: "ultrasound", meaning: "超声波", category: "chiropractic", emoji: "📡", example: "Ultrasound therapy reduces pain.", exampleCn: "超声波治疗减轻疼痛。" },
  { word: "traction", meaning: "牵引", category: "chiropractic", emoji: "↕️", example: "Traction helps decompress the spine.", exampleCn: "牵引帮助脊柱减压。" },
  { word: "decompression", meaning: "减压", category: "chiropractic", emoji: "⬇️", example: "Spinal decompression relieves pressure.", exampleCn: "脊椎减压缓解压力。" },

  // ==================== 症状与疼痛 Symptoms & Pain ====================
  { word: "pain", meaning: "疼痛", category: "symptoms", emoji: "😣", example: "Tell me where the pain is.", exampleCn: "告诉我哪里疼。" },
  { word: "ache", meaning: "酸痛", category: "symptoms", emoji: "😖", example: "I have an ache in my lower back.", exampleCn: "我下背部酸痛。" },
  { word: "soreness", meaning: "酸胀", category: "symptoms", emoji: "😫", example: "Muscle soreness is normal after exercise.", exampleCn: "运动后肌肉酸胀是正常的。" },
  { word: "numbness", meaning: "麻木", category: "symptoms", emoji: "😶", example: "Numbness in the fingers is a concern.", exampleCn: "手指麻木需要注意。" },
  { word: "tingling", meaning: "刺痛感", category: "symptoms", emoji: "⚡", example: "I feel tingling in my arm.", exampleCn: "我手臂有刺痛感。" },
  { word: "weakness", meaning: "无力", category: "symptoms", emoji: "😩", example: "Muscle weakness needs attention.", exampleCn: "肌肉无力需要注意。" },
  { word: "fatigue", meaning: "疲劳", category: "symptoms", emoji: "😴", example: "Rest when you feel fatigue.", exampleCn: "感到疲劳时要休息。" },
  { word: "spasm", meaning: "痉挛", category: "symptoms", emoji: "💢", example: "A muscle spasm can be painful.", exampleCn: "肌肉痉挛可能很疼。" },
  { word: "cramp", meaning: "抽筋", category: "symptoms", emoji: "😬", example: "Drink water to prevent cramps.", exampleCn: "喝水预防抽筋。" },
  { word: "strain", meaning: "拉伤", category: "symptoms", emoji: "🤕", example: "He has a muscle strain.", exampleCn: "他肌肉拉伤了。" },
  { word: "sprain", meaning: "扭伤", category: "symptoms", emoji: "🤕", example: "She sprained her ankle.", exampleCn: "她扭伤了脚踝。" },
  { word: "tear", meaning: "撕裂伤", category: "symptoms", emoji: "💔", example: "A muscle tear requires rest.", exampleCn: "肌肉撕裂需要休息。" },
  { word: "swelling", meaning: "肿胀", category: "symptoms", emoji: "🎈", example: "Ice helps reduce swelling.", exampleCn: "冰敷帮助消肿。" },
  { word: "bruise", meaning: "淤伤", category: "symptoms", emoji: "🟣", example: "The bruise will heal in a week.", exampleCn: "淤伤一周后会好。" },
  { word: "chronic", meaning: "慢性的", category: "symptoms", emoji: "📅", example: "Chronic pain lasts a long time.", exampleCn: "慢性疼痛持续很长时间。" },
  { word: "acute", meaning: "急性的", category: "symptoms", emoji: "⚡", example: "Acute pain comes on suddenly.", exampleCn: "急性疼痛突然发作。" },
  { word: "radiating", meaning: "放射性的", category: "symptoms", emoji: "☀️", example: "Radiating pain goes down the leg.", exampleCn: "放射性疼痛延伸到腿部。" },
  { word: "sharp", meaning: "剧烈的", category: "symptoms", emoji: "🔪", example: "I feel a sharp pain when I move.", exampleCn: "我移动时感到剧痛。" },
  { word: "dull", meaning: "隐隐的", category: "symptoms", emoji: "😑", example: "It's a dull ache in my back.", exampleCn: "我背部隐隐作痛。" },
  { word: "tender", meaning: "压痛", category: "symptoms", emoji: "👆", example: "The area is tender to touch.", exampleCn: "这个区域按压会痛。" },

  // ==================== 训练术语 Training Terms ====================
  { word: "rep", meaning: "次数", category: "training", emoji: "1️⃣", example: "Do 12 reps of each exercise.", exampleCn: "每个动作做12次。" },
  { word: "set", meaning: "组数", category: "training", emoji: "🔢", example: "Complete 3 sets of squats.", exampleCn: "完成3组深蹲。" },
  { word: "form", meaning: "动作姿势", category: "training", emoji: "📐", example: "Focus on proper form.", exampleCn: "注重正确的动作姿势。" },
  { word: "tempo", meaning: "节奏", category: "training", emoji: "🎵", example: "Control the tempo of your lifts.", exampleCn: "控制举重的节奏。" },
  { word: "volume", meaning: "训练量", category: "training", emoji: "📊", example: "Increase volume gradually.", exampleCn: "逐渐增加训练量。" },
  { word: "intensity", meaning: "强度", category: "training", emoji: "🔥", example: "High intensity burns more calories.", exampleCn: "高强度燃烧更多卡路里。" },
  { word: "frequency", meaning: "频率", category: "training", emoji: "📅", example: "Training frequency depends on your goals.", exampleCn: "训练频率取决于你的目标。" },
  { word: "progression", meaning: "渐进", category: "training", emoji: "📈", example: "Progression is key to improvement.", exampleCn: "渐进是进步的关键。" },
  { word: "overload", meaning: "超负荷", category: "training", emoji: "⬆️", example: "Progressive overload builds strength.", exampleCn: "渐进超负荷增强力量。" },
  { word: "recovery", meaning: "恢复", category: "training", emoji: "😌", example: "Recovery is as important as training.", exampleCn: "恢复和训练一样重要。" },
  { word: "rest", meaning: "休息", category: "training", emoji: "😴", example: "Take rest days between workouts.", exampleCn: "训练之间要有休息日。" },
  { word: "split", meaning: "分化训练", category: "training", emoji: "✂️", example: "I follow a push-pull split.", exampleCn: "我采用推拉分化训练。" },
  { word: "superset", meaning: "超级组", category: "training", emoji: "🔗", example: "Supersets save time.", exampleCn: "超级组节省时间。" },
  { word: "drop set", meaning: "递减组", category: "training", emoji: "⬇️", example: "Finish with a drop set.", exampleCn: "用递减组结束训练。" },
  { word: "failure", meaning: "力竭", category: "training", emoji: "😵", example: "Train to failure on the last set.", exampleCn: "最后一组练到力竭。" },
  { word: "plateau", meaning: "平台期", category: "training", emoji: "📉", example: "Change your routine to break a plateau.", exampleCn: "改变训练计划来突破平台期。" },
  { word: "PR", meaning: "个人纪录", category: "training", emoji: "🏆", example: "I hit a new PR today!", exampleCn: "我今天创造了新的个人纪录！" },
  { word: "max", meaning: "最大重量", category: "training", emoji: "🔝", example: "What's your max on bench press?", exampleCn: "你卧推最大重量是多少？" },
  { word: "warm-up set", meaning: "热身组", category: "training", emoji: "🔥", example: "Start with warm-up sets.", exampleCn: "从热身组开始。" },
  { word: "working set", meaning: "正式组", category: "training", emoji: "💪", example: "Now do your working sets.", exampleCn: "现在做正式组。" },

  // ==================== 营养与恢复 Nutrition & Recovery ====================
  { word: "protein", meaning: "蛋白质", category: "nutrition", emoji: "🥩", example: "Eat enough protein for muscle growth.", exampleCn: "摄入足够蛋白质促进肌肉生长。" },
  { word: "carbohydrate", meaning: "碳水化合物", category: "nutrition", emoji: "🍞", example: "Carbohydrates give you energy.", exampleCn: "碳水化合物给你能量。" },
  { word: "fat", meaning: "脂肪", category: "nutrition", emoji: "🧈", example: "Healthy fats are important.", exampleCn: "健康脂肪很重要。" },
  { word: "calorie", meaning: "卡路里", category: "nutrition", emoji: "🔥", example: "Count your calories for weight loss.", exampleCn: "减肥要计算卡路里。" },
  { word: "macro", meaning: "宏量营养素", category: "nutrition", emoji: "📊", example: "Track your macros daily.", exampleCn: "每天追踪宏量营养素。" },
  { word: "supplement", meaning: "补剂", category: "nutrition", emoji: "💊", example: "Supplements support your nutrition.", exampleCn: "补剂支持你的营养。" },
  { word: "hydration", meaning: "补水", category: "nutrition", emoji: "💧", example: "Hydration is crucial for performance.", exampleCn: "补水对运动表现至关重要。" },
  { word: "electrolyte", meaning: "电解质", category: "nutrition", emoji: "⚡", example: "Replace electrolytes after sweating.", exampleCn: "出汗后补充电解质。" },
  { word: "amino acid", meaning: "氨基酸", category: "nutrition", emoji: "🧬", example: "Amino acids build proteins.", exampleCn: "氨基酸构建蛋白质。" },
  { word: "creatine", meaning: "肌酸", category: "nutrition", emoji: "💪", example: "Creatine improves strength.", exampleCn: "肌酸提高力量。" },
  { word: "whey", meaning: "乳清蛋白", category: "nutrition", emoji: "🥛", example: "Drink whey protein after workout.", exampleCn: "训练后喝乳清蛋白。" },
  { word: "pre-workout", meaning: "训练前补剂", category: "nutrition", emoji: "⚡", example: "Pre-workout gives you energy.", exampleCn: "训练前补剂给你能量。" },
  { word: "post-workout", meaning: "训练后补剂", category: "nutrition", emoji: "🔄", example: "Have a post-workout shake.", exampleCn: "训练后喝蛋白奶昔。" },
  { word: "metabolism", meaning: "新陈代谢", category: "nutrition", emoji: "🔥", example: "Exercise boosts metabolism.", exampleCn: "运动促进新陈代谢。" },
  { word: "anabolic", meaning: "合成代谢", category: "nutrition", emoji: "📈", example: "Sleep is anabolic for muscles.", exampleCn: "睡眠对肌肉是合成代谢。" },
  { word: "catabolic", meaning: "分解代谢", category: "nutrition", emoji: "📉", example: "Avoid catabolic states.", exampleCn: "避免分解代谢状态。" },
  { word: "lean mass", meaning: "瘦体重", category: "nutrition", emoji: "💪", example: "Build lean mass with training.", exampleCn: "通过训练增加瘦体重。" },
  { word: "body fat", meaning: "体脂", category: "nutrition", emoji: "📏", example: "Reduce body fat with diet and exercise.", exampleCn: "通过饮食和运动减少体脂。" },
  { word: "BMI", meaning: "身体质量指数", category: "nutrition", emoji: "⚖️", example: "BMI is one health indicator.", exampleCn: "BMI是一个健康指标。" },
  { word: "DOMS", meaning: "延迟性肌肉酸痛", category: "nutrition", emoji: "😫", example: "DOMS peaks 24-48 hours after exercise.", exampleCn: "延迟性肌肉酸痛在运动后24-48小时达到高峰。" },

  // ==================== 专业术语 Professional Terms ====================
  { word: "biomechanics", meaning: "生物力学", category: "professional", emoji: "⚙️", example: "Biomechanics studies body movement.", exampleCn: "生物力学研究身体运动。" },
  { word: "kinesiology", meaning: "运动学", category: "professional", emoji: "🏃", example: "Kinesiology is the science of movement.", exampleCn: "运动学是研究运动的科学。" },
  { word: "anatomy", meaning: "解剖学", category: "professional", emoji: "🫀", example: "Study anatomy to understand the body.", exampleCn: "学习解剖学来了解身体。" },
  { word: "physiology", meaning: "生理学", category: "professional", emoji: "🧬", example: "Physiology explains how the body works.", exampleCn: "生理学解释身体如何运作。" },
  { word: "proprioception", meaning: "本体感觉", category: "professional", emoji: "🧠", example: "Proprioception helps with balance.", exampleCn: "本体感觉帮助平衡。" },
  { word: "neuromuscular", meaning: "神经肌肉的", category: "professional", emoji: "⚡", example: "Neuromuscular training improves coordination.", exampleCn: "神经肌肉训练改善协调性。" },
  { word: "musculoskeletal", meaning: "肌肉骨骼的", category: "professional", emoji: "🦴", example: "Musculoskeletal health is important.", exampleCn: "肌肉骨骼健康很重要。" },
  { word: "cardiovascular", meaning: "心血管的", category: "professional", emoji: "❤️", example: "Cardiovascular exercise strengthens the heart.", exampleCn: "心血管运动强化心脏。" },
  { word: "respiratory", meaning: "呼吸的", category: "professional", emoji: "🫁", example: "Cardio improves respiratory function.", exampleCn: "有氧运动改善呼吸功能。" },
  { word: "ergonomics", meaning: "人体工程学", category: "professional", emoji: "🪑", example: "Ergonomics prevents workplace injuries.", exampleCn: "人体工程学预防工作场所伤害。" },
  { word: "contraindication", meaning: "禁忌症", category: "professional", emoji: "🚫", example: "Check for contraindications before treatment.", exampleCn: "治疗前检查禁忌症。" },
  { word: "indication", meaning: "适应症", category: "professional", emoji: "✅", example: "What are the indications for this exercise?", exampleCn: "这个练习的适应症是什么？" },
  { word: "prognosis", meaning: "预后", category: "professional", emoji: "🔮", example: "The prognosis is good with proper care.", exampleCn: "适当护理后预后良好。" },
  { word: "bilateral", meaning: "双侧的", category: "professional", emoji: "↔️", example: "Do bilateral exercises for balance.", exampleCn: "做双侧练习来平衡。" },
  { word: "unilateral", meaning: "单侧的", category: "professional", emoji: "➡️", example: "Unilateral training fixes imbalances.", exampleCn: "单侧训练修复不平衡。" },
  { word: "anterior", meaning: "前面的", category: "professional", emoji: "⬆️", example: "The anterior muscles are in front.", exampleCn: "前面的肌肉在身体前侧。" },
  { word: "posterior", meaning: "后面的", category: "professional", emoji: "⬇️", example: "Work your posterior chain.", exampleCn: "锻炼你的后侧链。" },
  { word: "lateral", meaning: "侧面的", category: "professional", emoji: "↔️", example: "Lateral movement improves agility.", exampleCn: "侧向移动提高敏捷性。" },
  { word: "medial", meaning: "内侧的", category: "professional", emoji: "🎯", example: "The medial side is toward the center.", exampleCn: "内侧是朝向中心的一侧。" },
  { word: "proximal", meaning: "近端的", category: "professional", emoji: "📍", example: "Proximal means closer to the trunk.", exampleCn: "近端意味着更靠近躯干。" },
  { word: "distal", meaning: "远端的", category: "professional", emoji: "📍", example: "Distal means farther from the trunk.", exampleCn: "远端意味着离躯干更远。" },
  { word: "superficial", meaning: "浅层的", category: "professional", emoji: "🔝", example: "Superficial muscles are near the skin.", exampleCn: "浅层肌肉靠近皮肤。" },
  { word: "deep", meaning: "深层的", category: "professional", emoji: "⬇️", example: "Deep muscles support the spine.", exampleCn: "深层肌肉支撑脊柱。" },
  { word: "hypertrophy", meaning: "肌肥大", category: "professional", emoji: "💪", example: "Train for hypertrophy with moderate reps.", exampleCn: "用中等次数训练肌肥大。" },
  { word: "atrophy", meaning: "萎缩", category: "professional", emoji: "📉", example: "Muscle atrophy happens without use.", exampleCn: "不使用肌肉会萎缩。" }
];

// 分类信息
const categories = {
  anatomy: { name: "身体部位", emoji: "🦴", color: "#FF6B6B" },
  exercise: { name: "健身动作", emoji: "🏋️", color: "#4ECDC4" },
  equipment: { name: "健身器材", emoji: "🎯", color: "#45B7D1" },
  chiropractic: { name: "脊椎治疗", emoji: "🔧", color: "#96CEB4" },
  symptoms: { name: "症状疼痛", emoji: "😣", color: "#FFEAA7" },
  training: { name: "训练术语", emoji: "📊", color: "#DDA0DD" },
  nutrition: { name: "营养恢复", emoji: "🥗", color: "#98D8C8" },
  professional: { name: "专业术语", emoji: "📚", color: "#F7DC6F" }
};
